#!/usr/bin/env bash

# Purpose: Evaluate the quality of genome assemblies using QUAST

# Tool:
# QUAST v5.2.0

# Inputs:
# - `*.fasta`: Assembly files generated by different assemblers
# - `*.TAIR10.dna.toplevel.fa`: Reference genome 
# - `*.TAIR10.57.gff3`: GFF3 file for annotations

# Outputs:
# - `quastEdi-0/`: QUAST reports and statistics

###############################################################################

#SBATCH --cpus-per-task=16
#SBATCH --time=1-00:00:00
#SBATCH --mem=64G
#SBATCH --partition=pibu_el8
#SBATCH --job-name=quast
#SBATCH --mail-user=ana.castromarquez@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/data/users/acastro/genome_assembly_annotation/log/output_quast_%j.o
#SBATCH --error=/data/users/acastro/genome_assembly_annotation/log/error_quast_%j.e

# Go to working directory
cd /data/users/$USER/genome_assembly_annotation

# Reference genome directory
DATA_DIR_EDI_REF=/data/users/$USER/genome_assembly_annotation/raw_data/references

# Input directories for assemblies
DIR_FLYE_EDI=/data/users/$USER/genome_assembly_annotation/analysis/flyeEdi-0
DIR_HIFIASM_EDI=/data/users/$USER/genome_assembly_annotation/analysis/hifiasmEdi-0
DIR_LJA_EDI=/data/users/$USER/genome_assembly_annotation/analysis/ljaEdi-0

# Output directory for QUAST results
DIR_QUAST_EDI=/data/users/$USER/genome_assembly_annotation/analysis/quastEdi-0

# Generate a soft link for reference genome Arabidopsis_thaliana
ln -s /data/courses/assembly-annotation-course/references $DATA_DIR_EDI_REF

# Create directory to save QUAST results
mkdir --parents $DIR_QUAST_EDI

# Run QUAST to evaluate assemblies
apptainer exec /containers/apptainer/quast_5.2.0.sif \
    quast.py \
    --eukaryote \
    --threads 16 \
    --est-ref-size 154000000 \
    --labels FLYE,HIFIASM,LJA \
    --reference $DATA_DIR_EDI_REF/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa \
    --features $DATA_DIR_EDI_REF/Arabidopsis_thaliana.TAIR10.57.gff3 \
    $DIR_FLYE_EDI/assembly.fasta \
    $DIR_HIFIASM_EDI/hifiasm_output.bp.p_ctg.fa \
    $DIR_LJA_EDI/assembly.fasta \
    --output $DIR_QUAST_EDI
