#!/usr/bin/env bash

# Purpose: Evaluate the quality of genome assemblies without using a reference genome

# Tool:
# QUAST v5.2.0

# Inputs:
# - `*.fasta`: Assembly files generated by different assemblers.

# Outputs:
# - `quastEdi-0/noreference/`: QUAST reports and statistics without reference

###############################################################################

#SBATCH --cpus-per-task=16
#SBATCH --time=1-00:00:00
#SBATCH --mem=64G
#SBATCH --partition=pibu_el8
#SBATCH --job-name=quast_no_reference
#SBATCH --mail-user=ana.castromarquez@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/data/users/acastro/genome_assembly_annotation/log/output_quast_no_reference_%j.o
#SBATCH --error=/data/users/acastro/genome_assembly_annotation/log/error_quast_no_reference_%j.e

# Go to working directory
cd /data/users/$USER/genome_assembly_annotation

# Input directories for assemblies
DIR_FLYE_EDI=/data/users/$USER/genome_assembly_annotation/analysis/flyeEdi-0
DIR_HIFIASM_EDI=/data/users/$USER/genome_assembly_annotation/analysis/hifiasmEdi-0
DIR_LJA_EDI=/data/users/$USER/genome_assembly_annotation/analysis/ljaEdi-0

# Output directory for QUAST results
DIR_QUAST_EDI=/data/users/$USER/genome_assembly_annotation/analysis/quastEdi-0/noreference

# Create directories to save results
mkdir --parents $DIR_QUAST_EDI

# Run QUAST without a reference
apptainer exec /containers/apptainer/quast_5.2.0.sif \
    quast.py \
    --eukaryote \
    --threads 16 \
    --est-ref-size 154000000 \
    --labels FLYE,HIFIASM,LJA \
    $DIR_FLYE_EDI/assembly.fasta \
    $DIR_HIFIASM_EDI/hifiasm_output.bp.p_ctg.fa \
    $DIR_LJA_EDI/assembly.fasta \
    --output $DIR_QUAST_EDI
