#!/usr/bin/env bash

# Purpose: Perfom Homology-Based Genome Annotation using MAKER pipeline

# Tools:
# - MAKER v3.01.03
# - OpenMPI/4.1.1-GCC-10.3.0
# - RepeatMasker
# - AUGUSTUS

# Inputs:
# - `maker_control_files`:
#   - `maker_opts.ctl`: Main options control file for MAKER (modified)
#   - `maker_bopts.ctl`: Control file for basic options
#   - `maker_evm.ctl`: Control file for the Evidence Modeler (EVM)
#   - `maker_exe.ctl`: Control file specifying the paths to the executables
# - `trinityRNA`: 
#   - `trinityRNA.Trinity.fasta`: The FASTA file generated by the Trinity RNA-Seq assembler
# - `flyeEdi-0`: 
#   - `assembly.fasta`: The FASTA file containing the genome assembly from Flye
# - `edtaEdi-0/flye`
#   - `assembly.fasta.mod.EDTA.TElib.fa`: The FASTA file containing the repeat library for the genome

# Outputs:
# - `assembly.maker.output/`
#   - `assembly_master_datastore_index.log`: Log containing paths to individual GFF and FASTA files
#   - Additional files and directories

###############################################################################

#SBATCH --cpus-per-task=4
#SBATCH --time=3-00:00:00
#SBATCH --mem=64G
#SBATCH --partition=pibu_el8
#SBATCH --job-name=maker_homology_based
#SBATCH --mail-user=ana.castromarquez@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/data/users/acastro/genome_assembly_annotation/log/output_maker_homology_based_%j.o
#SBATCH --error=/data/users/acastro/genome_assembly_annotation/log/error_maker_homology_based_%j.e

# Go to working directory
cd /data/users/$USER/genome_assembly_annotation

# Set up RepeatMasker
REPEATMASKER_DIR="/data/courses/assembly-annotation-course/CDS_annotation/softwares/RepeatMasker"
export PATH=$PATH:"$REPEATMASKER_DIR"
COURSEDIR="/data/courses/assembly-annotation-course/CDS_annotation"

# Directories for input data and control files
DIR_CONTROL_FILES=/data/users/acastro/genome_assembly_annotation/analysis/maker_control_files
DIR_TRINITY_RNA=/data/users/$USER/genome_assembly_annotation/analysis/trinityRNA/trinityRNA.Trinity.fasta
DIR_FLYE_EDI=/data/users/$USER/genome_assembly_annotation/analysis/flyeEdi-0/assembly.fasta
DIR_REPEAT_LIBRARY=/data/users/acastro/genome_assembly_annotation/analysis/edtaEdi-0/flye/assembly.fasta.mod.EDTA.TElib.fa
MAKER_FILES=/data/users/acastro/genome_assembly_annotation/analysis/maker_RNA_seq

# Create directory
mkdir --parents $DIR_MAKER

# Load modules
module load OpenMPI/4.1.1-GCC-10.3.0
module load AUGUSTUS/3.4.0-foss-2021a

# Run MAKER with MPI
mpiexec --oversubscribe -n 50 apptainer exec \
    --bind $SCRATCH:/TMP --bind /data --bind $AUGUSTUS_CONFIG_PATH --bind $REPEATMASKER_DIR \
    /data/courses/assembly-annotation-course/CDS_annotation/containers/MAKER_3.01.03.sif \
    maker -mpi --ignore_nfs_tmp -TMP /TMP \
    $DIR_CONTROL_FILES/maker_opts.ctl \
    $DIR_CONTROL_FILES/maker_bopts.ctl \
    $DIR_CONTROL_FILES/maker_evm.ctl \
    $DIR_CONTROL_FILES/maker_exe.ctl
